const TimetoStartGame = 500; //delay to start the game
const FlashDelay = 200;  // delay between colours
const changeButtonColour = ['green', 'red', 'yellow', 'blue']; // colours class names

let gameSpeed = 0; //var for game speed
let userResponse = [];  //empty array to hold sequence generated by user clicks
let sequence = []; //sequence ramdomly generated by JS
let bestResult = 0; // displays the best result of the game

// function that starts and restarts the game once button "start" is pressed

function startGame(){
    // set the arrays to empty and speed to 800
    sequence = []; // it empties the sequence array when a new game starts
    userResponse = []; // it empties the usersequence array when a new game starts
    gameSpeed = 800;
    document.getElementById('current').innerHTML = 0; // set the score of the current game to 0
    document.getElementById("lightIndicator").style.backgroundColor = "chartreuse"; // changes the light indicator colour from red to green
   
    setTimeout(function () { // function responsible for calling the delay for starting new game
        nextRound()
    }, TimetoStartGame);
   
}

function blinkGameOver() { // function that make all lights blinking when game is over
    gameSpeed = 800;
    for(let i = 0; i < 4; i++) {
        flashColours(i);
    }
}

function youLost() { // function that sets an intervall between the blinkGameOver function
    gameSpeed = 800;
    for(let i = 0; i < 5; i++) {
        setTimeout(blinkGameOver, 1000 * i);
    }
}

function generateNextNumber() {  //function generates numbers ramdomly from 0 to 3 
    return Math.floor(Math.random() * 4);
}

function nextRound() {  // function called when the user clicks on correct colour 
    const nextNum = generateNextNumber(); // generates next number to flash other colour
    sequence.push(nextNum) //adds them number to the array "sequence"
    if (sequence.length == 5 || sequence.length == 9 || sequence.length == 13) {
        gameSpeed -= 200; // makes game faster when the user is at its 5th,,9th or 13th click
    
    }
    for (let i = 0; i< sequence.length; i++) {
        const n = sequence[i]; // saves the sequence of generated number to array
        setTimeout(function () {
            flashColours(n) //call function passing the array to the function
        }, gameSpeed  * i) //sets intervals between the colours flashed , it increases for each element of the array 
    }

}

function flashColours(buttonId){ 
    //flashes colours according to sequence that repeats right clicked colours saved on array
    
    document.getElementById(buttonId).classList.remove(changeButtonColour[buttonId]); 
    //gets the id of each colour button and removes the css class to make the flash effect 
    
    setTimeout(function() {
        document.getElementById(buttonId).classList.add(changeButtonColour[buttonId])
    }, gameSpeed - 200);
 //gets the id of each colour button and adds back the css class to make the flash effect 
    
}

function scoreCounter(button){          // counter for points for current game
    let value = button.getAttribute('id'); 
    userResponse.push(value);  // adds the id of the button to the array "userResponse"
    flashColours(value); //do the flashing when user repeats sequence
    setTimeout(checkResult, 2000) // set interval before calling the function
} 

function checkResult() {
    const position = userResponse.length - 1; // takes one so arrays can be compared 
    if(userResponse[position] != sequence[position]) { // checks if arrays don't have the same sequence
        maxScore(); // user loses and calls this 3 functions
        youLost();
        resetGame();
    } else if (userResponse.length == sequence.length) { //if the length of the arrays is the same the game goes on
        document.getElementById('current').innerHTML = userResponse.length //the value of the score, in the userResponse lenght of the array variable is displayed on the right side of the start button div 
        userResponse = [] 
        nextRound()
    }
}
function resetGame() {  // when user loses the indicator light turns back to red
    document.getElementById("lightIndicator").style.backgroundColor = "red";
}
function maxScore() { // the value of the score, in the bestResult(best score of all games) variable is displayed on the left side of the start button div and stays unless page is refreshed
    bestResult = Math.max(parseInt(document.getElementById('current').innerHTML), bestResult);
    document.getElementById('bestScore').innerHTML =  bestResult
}


// for this assignment I consulted 3wschools, stackoverflow and the extra video from the lecturer